#########################################################################################
#██╗████████╗███████╗███╗░░░███╗░██████╗██╗░░██╗░█████╗░██████╗░██████╗░██████╗░░█████╗░#
#██║╚══██╔══╝██╔════╝████╗░████║██╔════╝██║░░██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗#
#██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░███████║██║░░██║██████╔╝██████╔╝██████╔╝██║░░██║#
#██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗██╔══██║██║░░██║██╔═══╝░██╔═══╝░██╔══██╗██║░░██║#
#██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝██║░░██║╚█████╔╝██║░░░░░██║░░░░░██║░░██║╚█████╔╝#
#╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═╝░░░░░╚═╝░░╚═╝░╚════╝░#
#########################################################################################
# By github.com/novialriptide (Novial)

lang: "en-us"
shoplist-max: 7