#########################################################################################
#██╗████████╗███████╗███╗░░░███╗░██████╗██╗░░██╗░█████╗░██████╗░██████╗░██████╗░░█████╗░#
#██║╚══██╔══╝██╔════╝████╗░████║██╔════╝██║░░██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗#
#██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░███████║██║░░██║██████╔╝██████╔╝██████╔╝██║░░██║#
#██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗██╔══██║██║░░██║██╔═══╝░██╔═══╝░██╔══██╗██║░░██║#
#██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝██║░░██║╚█████╔╝██║░░░░░██║░░░░░██║░░██║╚█████╔╝#
#╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═╝░░░░░╚═╝░░╚═╝░╚════╝░#
#########################################################################################
# By github.com/novialriptide (Novial)

lang: en-us
