name: ItemShopPro
main: me.novial.itemshoppro.Main
author: Novial
version: 1.1
api-version: 1.13
commands:
  itemshoppro:
    description: Shows information about the plugin.
    usage: /<command>
    permission: itemshoppro.info
  createshop:
    description: Creates a shop.
    usage: /<command> productQuantity product currencyQuantity currency
    permission: itemshoppro.createshop