name: ItemShopPro
main: me.novial.itemshoppro.Main
author: Novial
version: 1.1
api-version: 1.13
commands:
  itemshoppro:
    description: Shows information about the plugin.
    usage: /<command>
    permission: itemshoppro.info
  createshop:
    description: Creates a shop.
    usage: /<command> <Product Quantity> <Product> <Currency Quantity> <Currency>
    permission: itemshoppro.createshop
  shops:
    description: Gives a list of registered shops
    usage: /<command> <Page>
    permission: itemshoppro.shops